export type NationalPortalNode = {
  id: string;
  category: "Central Govt Portal" | "IPR & Business Registry" | "State Govt Portal" | "Research & Telemetry";
  name: string;
  stateOrRegion: string;
  url: string;
  description: string;
  keyServices: string[];
  fetchingMethod: "DIRECT_REST_API" | "AEM_HTML_DOM" | "ANGULAR_SPA" | "TLS_SECURE_SCRAPER";
};

export const ALL_NATIONAL_AND_STATE_PORTALS: NationalPortalNode[] = [
  // ============================================================
  //  1. CENTRAL GOVERNMENT PORTALS & IPR / BUSINESS REGISTRIES
  // ============================================================
  {
    id: "portal-startup-india",
    category: "Central Govt Portal",
    name: "Startup India (DPIIT)",
    stateOrRegion: "Central",
    url: "https://www.startupindia.gov.in/",
    description: "Flagship Government of India startup portal managing DPIIT recognition, SISFS Seed Fund, CGSS Credit Guarantee, and 80-IAC Tax Exemption.",
    keyServices: ["DPIIT Recognition", "SISFS Seed Grant (₹20L)", "CGSS Credit Guarantee (₹10Cr)", "Section 80-IAC Tax Holiday"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-ipindia",
    category: "IPR & Business Registry",
    name: "Indian Patent Office & Trademark Registry (IP India)",
    stateOrRegion: "Central",
    url: "https://ipindia.gov.in/",
    description: "Official Intellectual Property India portal for Patent filing, Trademark public search, Design registration, and 80% fee rebate for startups.",
    keyServices: ["Patent Public Search", "Trademark Registry", "Fast-Track Patent Examination", "SIPP IP Facilitators"],
    fetchingMethod: "TLS_SECURE_SCRAPER",
  },
  {
    id: "portal-mca",
    category: "IPR & Business Registry",
    name: "Ministry of Corporate Affairs (MCA V3 Portal)",
    stateOrRegion: "Central",
    url: "https://www.mca.gov.in/",
    description: "Company incorporation and compliance portal for Private Limited Companies, LLPs, One Person Companies (OPC), and SPICe+ forms.",
    keyServices: ["SPICe+ Company Incorporation", "RUN Name Reservation", "LLP Registration", "DIN / DSC Issuance"],
    fetchingMethod: "TLS_SECURE_SCRAPER",
  },
  {
    id: "portal-gem",
    category: "Central Govt Portal",
    name: "Government e-Marketplace (GeM Portal)",
    stateOrRegion: "Central",
    url: "https://gem.gov.in/",
    description: "National public procurement marketplace offering EMD exemption and tender relaxations for DPIIT recognized startups.",
    keyServices: ["Startup Runway Portal", "EMD Exemption", "Public Procurement Relaxations", "Direct Govt Orders"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-udyam",
    category: "IPR & Business Registry",
    name: "MSME Udyam Registration Portal",
    stateOrRegion: "Central",
    url: "https://udyamregistration.gov.in/",
    description: "Official MSME registration portal providing Udyam Certificates for micro, small, and medium enterprises.",
    keyServices: ["Udyam Certificate", "Priority Sector Lending", "Delayed Payment Dispute Portal (Samadhaan)", "Subsidized Credit"],
    fetchingMethod: "DIRECT_REST_API",
  },
  {
    id: "portal-dst-nidhi",
    category: "Central Govt Portal",
    name: "DST NIDHI Portal",
    stateOrRegion: "Central",
    url: "https://nidhi.dst.gov.in/",
    description: "Department of Science & Technology national innovation pipeline funding PoCs, EIR fellowships, and incubator seed funds.",
    keyServices: ["NIDHI-PRAYAS 2.0 (₹10L PoC)", "NIDHI-EIR Fellowship (₹30k/mo)", "NIDHI-SSP (₹1Cr Seed Capital)", "NIDHI-CoE (₹50Cr)"],
    fetchingMethod: "DIRECT_REST_API",
  },
  {
    id: "portal-msh",
    category: "Central Govt Portal",
    name: "MeitY Startup Hub (MSH)",
    stateOrRegion: "Central",
    url: "https://msh.meity.gov.in/",
    description: "Ministry of Electronics & IT hub backing deep-tech, AI, IoT, cybersecurity, and semiconductor chip design startups.",
    keyServices: ["SAMRIDH Accelerator Matching Fund (₹40L)", "TIDE 2.0 Grant (₹7L / ₹40L)", "GENESIS (₹490Cr Tier-2/3 Cities)", "Chips to Startup (C2S)"],
    fetchingMethod: "ANGULAR_SPA",
  },
  {
    id: "portal-birac",
    category: "Central Govt Portal",
    name: "BIRAC (Biotechnology Industry Research Assistance Council)",
    stateOrRegion: "Central",
    url: "https://birac.nic.in/",
    description: "Department of Biotechnology (DBT) enterprise funding biotech, medtech, agritech, and healthcare innovations.",
    keyServices: ["BIRAC BIG Scheme (₹50L)", "SPARSH Social Innovation", "PACE Academic R&D", "BioNEST Incubators Network"],
    fetchingMethod: "TLS_SECURE_SCRAPER",
  },
  {
    id: "portal-idex",
    category: "Central Govt Portal",
    name: "Innovations for Defence Excellence (iDEX)",
    stateOrRegion: "Central",
    url: "https://idex.gov.in/challenges",
    description: "Ministry of Defence portal offering grants for Defence India Startup Challenges (DISC 14), iDEX Prime, ADITI, and SPARK Grants.",
    keyServices: ["iDEX SPARK Grant (₹1.5Cr)", "iDEX Prime Grant (₹10Cr)", "ADITI Scheme (₹25Cr)", "DISC 14 Armed Forces Tenders"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-isti",
    category: "Research & Telemetry",
    name: "India Science, Technology & Innovation (ISTI)",
    stateOrRegion: "Central",
    url: "https://www.indiascienceandtechnology.gov.in/",
    description: "National repository for R&D indicators, national laboratory equipment, fellowships, and tech transfer opportunities.",
    keyServices: ["S&T Telemetry", "National Lab Access", "Ramanujan & WISE-KIRAN Fellowships", "R&D Grant Registry"],
    fetchingMethod: "TLS_SECURE_SCRAPER",
  },

  // ============================================================
  //  2. ALL 28 INDIAN STATES & UNION TERRITORIES PORTALS
  // ============================================================
  {
    id: "portal-gujarat",
    category: "State Govt Portal",
    name: "Startup Gujarat Portal",
    stateOrRegion: "Gujarat",
    url: "https://startup.gujarat.gov.in/",
    description: "Official Gujarat Government startup portal for Sustenance Allowance, Prototype Grants, and Standard Operating Procedures (SOPs 1-5).",
    keyServices: ["Sustenance Allowance (₹20k/mo)", "Prototype Grant (₹30L)", "SOP 1-5 Workflows", "Nodal Institutes Network"],
    fetchingMethod: "DIRECT_REST_API",
  },
  {
    id: "portal-up",
    category: "State Govt Portal",
    name: "StartInUP Uttar Pradesh Portal",
    stateOrRegion: "Uttar Pradesh",
    url: "https://startinup.up.gov.in/",
    description: "Uttar Pradesh IT & Electronics Department portal offering monthly sustenance allowance, seed capital, and CoE grants.",
    keyServices: ["Sustenance Allowance (₹17,500/mo)", "Seed Capital (₹5L)", "Market Access (₹7.5L)", "CoE AI & Drones Grants (₹10Cr)"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-wb",
    category: "State Govt Portal",
    name: "West Bengal Startup Portal & STEP IIT Kharagpur",
    stateOrRegion: "West Bengal",
    url: "https://startup.wb.gov.in/",
    description: "West Bengal MSME & STEP IIT Kharagpur incubation portal backing deep-tech ventures out of Eastern India.",
    keyServices: ["STEP IIT KGP Incubation Seed Fund (₹25L)", "WB Innovation Hub", "DeepTech Acceleration", "Faculty R&D Scraper"],
    fetchingMethod: "DIRECT_REST_API",
  },
  {
    id: "portal-karnataka",
    category: "State Govt Portal",
    name: "Startup Karnataka (Elevate)",
    stateOrRegion: "Karnataka",
    url: "https://startup.karnataka.gov.in/",
    description: "Karnataka Innovation & Technology Society flagship portal backing early-stage tech founders across Bengaluru and Tier-2 hubs.",
    keyServices: ["Elevate Idea2POC Grant (up to ₹50L)", "Patent Cost Reimbursement", "Venture Capital Equity Fund", "KTech Innovation Hubs"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-kerala",
    category: "State Govt Portal",
    name: "Kerala Startup Mission (KSUM)",
    stateOrRegion: "Kerala",
    url: "https://startupmission.kerala.gov.in/",
    description: "Kerala Government apex agency for startup ecosystem development, Fab Labs, and innovation grants.",
    keyServices: ["KSUM Innovation Grant (₹12L)", "Fab Lab Prototyping Access", "Scaleup Fund", "Global Linkage Grants"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-maharashtra",
    category: "State Govt Portal",
    name: "Maharashtra State Innovation Society (MSINS)",
    stateOrRegion: "Maharashtra",
    url: "https://msins.in/",
    description: "Maharashtra State Innovation Society portal managing Grand Challenges, seed funds, and patent fee reimbursements.",
    keyServices: ["MSINS Seed Fund", "Patent Fee Reimbursement (₹2L)", "Quality Certification Support", "Govt Grand Challenges"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-telangana",
    category: "State Govt Portal",
    name: "T-Hub & Startup Telangana",
    stateOrRegion: "Telangana",
    url: "https://t-hub.co/",
    description: "Telangana Government technology incubator and innovation ecosystem hub supporting AI, Hardware, and HealthTech.",
    keyServices: ["T-Hub Incubation & Acceleration", "T-Fund Seed Capital", "WE-Hub Women Entrepreneurship Fund", "TSIC Social Innovation"],
    fetchingMethod: "ANGULAR_SPA",
  },
  {
    id: "portal-rajasthan",
    category: "State Govt Portal",
    name: "iStart Rajasthan Portal",
    stateOrRegion: "Rajasthan",
    url: "https://istart.rajasthan.gov.in/",
    description: "Single window portal for Rajasthan startups offering Sustenance Allowance, QRate ranking, and Bipasha incubation hubs.",
    keyServices: ["Sustenance Allowance (₹20k/mo)", "Seed Capital (₹5L)", "QRate Startup Ranking", "Techno Hub Incubation"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-tn",
    category: "State Govt Portal",
    name: "StartupTN (Tamil Nadu Startup Mission)",
    stateOrRegion: "Tamil Nadu",
    url: "https://startuptn.in/",
    description: "Tamil Nadu Government startup agency supporting TANSEED grants, SC/ST startup hubs, and regional innovation circles.",
    keyServices: ["TANSEED Grant (₹10L)", "SC/ST Startup Fund", "Regional Hub Grants", "Global Tamil Startup Investor Circle"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-punjab",
    category: "State Govt Portal",
    name: "Startup Punjab Portal",
    stateOrRegion: "Punjab",
    url: "https://startup.punjab.gov.in/",
    description: "Department of Industries & Commerce Punjab portal backing Agritech, Food Processing, and IT startups.",
    keyServices: ["Seed Capital Support (₹3L)", "Interest Subsidy (5%)", "Lease Rent Subvention", "Incubator Capital Grant"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-odisha",
    category: "State Govt Portal",
    name: "Startup Odisha Portal",
    stateOrRegion: "Odisha",
    url: "https://startupodisha.gov.in/",
    description: "MSME Department Odisha portal managing monthly allowance, product development grants, and O-Hub incubation center.",
    keyServices: ["Monthly Allowance (₹20,000/mo)", "Product Development Grant (₹15L)", "O-Hub World Class Incubation", "IPR Support"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-bihar",
    category: "State Govt Portal",
    name: "Startup Bihar Portal",
    stateOrRegion: "Bihar",
    url: "https://startup.bihar.gov.in/",
    description: "Department of Industries Bihar portal providing interest-free seed loans and prototype grants.",
    keyServices: ["Interest-Free Seed Loan (₹10L)", "Incubator Matching Grant", "SC/ST & Women Founder Bonus (15%)", "CoE Grants"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-assam",
    category: "State Govt Portal",
    name: "Startup Assam (The Nest)",
    stateOrRegion: "Assam",
    url: "https://startup.assam.gov.in/",
    description: "Industries & Commerce Department Assam portal nurturing North-East tech ventures through The Nest incubation hub.",
    keyServices: ["MASI Seed Capital (₹5L)", "Sustenance Allowance (₹20k/mo)", "The Nest Incubation Support", "Scaleup Subsidy"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-goa",
    category: "State Govt Portal",
    name: "Startup Goa Portal",
    stateOrRegion: "Goa",
    url: "https://startups.goa.gov.in/",
    description: "Department of Information Technology Goa portal providing salary subventions, seed capital, and patent reimbursements.",
    keyServices: ["Salary Subvention (up to ₹10k/emp)", "Seed Capital (₹10L)", "Trademark & Patent Reimbursement", "Co-Working Subvention"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-haryana",
    category: "State Govt Portal",
    name: "Startup Haryana Portal",
    stateOrRegion: "Haryana",
    url: "https://startupharyana.gov.in/",
    description: "Department of IT & Electronics Haryana portal supporting lease rent subvention, patent grants, and seed funds.",
    keyServices: ["Seed Grant (₹10L)", "Lease Rent Subvention (50%)", "Patent Reimbursement (₹2L)", "Net SGST Reimbursement"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-mp",
    category: "State Govt Portal",
    name: "Startup MP (MP Startup Centre)",
    stateOrRegion: "Madhya Pradesh",
    url: "https://startup.mp.gov.in/",
    description: "Department of MSME, Government of Madhya Pradesh official portal (MP Startup Policy 2022) offering state innovation challenges, JAN-SEVA e-services, product development assistance, and patent support.",
    keyServices: ["State Innovation Challenge Grant (₹1 Crore)", "Product Development Assistance (₹15 Lakhs)", "Lease Rent Reimbursement (₹5L/yr)", "Patent Filing Reimbursement (₹5L)", "JAN-SEVA MP E-Services Portal"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-uk",
    category: "State Govt Portal",
    name: "Startup Uttarakhand Portal",
    stateOrRegion: "Uttarakhand",
    url: "https://startuputtarakhand.uk.gov.in/",
    description: "Industries Department Uttarakhand portal backing mountain economy, eco-tourism, and biotech ventures.",
    keyServices: ["Monthly Allowance (₹15k/mo)", "Seed Capital (₹10L)", "Biotech & Organic Farming Incentives", "IPR Reimbursement"],
    fetchingMethod: "AEM_HTML_DOM",
  },
  {
    id: "portal-delhi",
    category: "State Govt Portal",
    name: "Delhi Startup Policy Portal",
    stateOrRegion: "Delhi NCR",
    url: "https://startup.delhi.gov.in/",
    description: "Government of NCT Delhi portal offering collateral-free loans, mentor networks, and procurement relaxations.",
    keyServices: ["Collateral-Free Loans", "Financial Assistance for Patents", "Delhi Task Force Incubation", "Procurement Exemption"],
    fetchingMethod: "AEM_HTML_DOM",
  },
];

export function getNationalAndStatePortalRegistry() {
  return {
    totalPortals: ALL_NATIONAL_AND_STATE_PORTALS.length,
    centralGovtPortalsCount: ALL_NATIONAL_AND_STATE_PORTALS.filter((p) => p.category === "Central Govt Portal").length,
    iprAndBusinessRegistriesCount: ALL_NATIONAL_AND_STATE_PORTALS.filter((p) => p.category === "IPR & Business Registry").length,
    stateGovtPortalsCount: ALL_NATIONAL_AND_STATE_PORTALS.filter((p) => p.category === "State Govt Portal").length,
    researchAndTelemetryCount: ALL_NATIONAL_AND_STATE_PORTALS.filter((p) => p.category === "Research & Telemetry").length,
    registry: ALL_NATIONAL_AND_STATE_PORTALS,
  };
}
